Update AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_S…
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #157
Opened 2021-11-18 19:10 UTC by MOC-Labs-Review

…tyles.md

**Replace issue name M00-LAB00:QUICK_DESCRIPTION, for example "M01-LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes # . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]":
- [ ] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [ ] Tested it
- [ ] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

-
-
-

2021-11-18 19:10 UTC, MOC-Labs-Review commented
Submitted by garjen55 on behalf of MOC Labs Review

2021-11-23 15:23 UTC, unaihuete93 commented
@MOC-Labs-Review Next time at least provide description and follow guidelines as mentioned in the PR template if possible [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) thanks!

2021-11-23 16:02 UTC, unaihuete93 requested changes

2021-11-23 16:02 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
> +    - agent.name -equals az400m05-vm0:
```suggestion
    - agent.name -equals az400m05-vm0
```
not correct, it works without ":"

2021-12-01 15:23 UTC, unaihuete93 commented
closing until feedback is received

2021-12-01 15:23 UTC, closed without merging