Lab5 Proposal (Michael and Clementino involved)
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #19
Opened 2021-01-18 17:30 UTC by unaihuete93

# Module: 5
## Lab/Demo: Lab: Configuring Agent Pools and Understanding Pipeline Styles

Changes proposed in this pull request:

- use the LAB VM (LOD) instead of Azure VM, making the lab easier for the concepts we want to be showing
-
-

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft requested changes
Hi Unai, please take a look at the suggestions below.

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      [System.IO.Compression.ZipFile]::ExtractToDirectory("$HOME\Downloads\vsts-agent-win-x64-2.179.0.zip", "$PWD")
Instead of "2.179.0", there should be a placeholder for the version. The download file version will change frequently.

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      | Enter personal access token | the access token you recorded earlier in this task |
Not your change, but in the previous line, "**Enter** key" should be just Enter. Also, what do and Michael think about saying "Press Enter" instead. It wasn't clear to some students what "Enter" meant.

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
> +1.  Within the LOD VM (Lab VM), start a web browser, navigate to [the Azure DevOps portal](https://dev.azure.com) and sign in by using the Microsoft account associated with your Azure DevOps organiza
Let's replace "LOD VM" by just "Lab Virtual machine (Lab VM) or your own computer". This lab should not depend on a particular vendor VM or being on a VM at all.

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
This comment is not related to this line, but to the line above "Estimated time: **90 minutes**". Could you switch it to "45 minutes" (It was actually less when tested in class).

Also the whole sections above on "Prepare an Azure subscription" and "Set up a GitHub account" are not needed.

2021-02-04 02:48 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      | Enter run agent as service? (Y/N) (press enter for N) | **Enter** |
I prefer saying Y have it run as a service, in case the student needs to reboot the VM. Choose so also makes unnecessary the next question on autologon.

2021-02-04 03:11 UTC, ClementinoDeMendonca-msft commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
> +1.  On the **Runs** tab of the **PartsUnlimitedE2E** pane, in the upper right corner, click the vertical ellipsis (three vertical dots) symbol and, in the dropdown menu, click **Export to YAML**. Thi
The exported yaml file is actually called "PartsUnlimitedE2E.yml" not "build.yml".

2021-02-08 17:25 UTC, unaihuete93 commented
All fixes proposed in comments added 👍  @ClementinoDeMendonca-msft

2021-02-08 17:25 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      [System.IO.Compression.ZipFile]::ExtractToDirectory("$HOME\Downloads\vsts-agent-win-x64-2.179.0.zip", "$PWD")
Done :)

2021-02-08 17:25 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      | Enter personal access token | the access token you recorded earlier in this task |
Done :)

2021-02-08 17:25 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
> +1.  Within the LOD VM (Lab VM), start a web browser, navigate to [the Azure DevOps portal](https://dev.azure.com) and sign in by using the Microsoft account associated with your Azure DevOps organiza
Done :)

2021-02-08 17:25 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Done :)

2021-02-08 17:26 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
>      | Enter run agent as service? (Y/N) (press enter for N) | **Enter** |
Done :)

2021-02-08 17:26 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
> +1.  On the **Runs** tab of the **PartsUnlimitedE2E** pane, in the upper right corner, click the vertical ellipsis (three vertical dots) symbol and, in the dropdown menu, click **Export to YAML**. Thi
Done :)

2021-02-08 22:22 UTC, ClementinoDeMendonca-msft approved these changes
Thank you Unai, this will expedite doing this lab, allowing students to focus on  Azure DevOps instead of a side topic on creating a virtual machine. At that the first part was more of an AZ-104 lab.

2021-02-09 16:33 UTC, unaihuete93 commented
conflict resolved, we should be able to approve the PR now :)

2021-02-10 10:35 UTC, unaihuete93 commented
Added Preethi´s proposals from MS Teams chat

2021-02-20 17:05 UTC, merged