Wiki lab fixes
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #21
Opened 2021-01-19 09:55 UTC by unaihuete93

# Module: 3
## Lab/Demo: Sharing Team Knowledge using Azure Project Wikis

Fixes # .

Changes proposed in this pull request:

- missing steps and clarifications 
-
-

2021-01-19 15:27 UTC, mkennten commented on Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
> +1.  In the vertical menu on the left side, click **Repos**, in the upper section of the **Files** pane, make sure you have  the **TailwindTraders-Website** repo selected (choose it from the dropdown
@unaihuete93 Can you please change "git icon" to "Git icon"

2021-01-19 15:33 UTC, mkennten commented on Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
> +1.  On you lab computer, in the Azure DevOps portal displaying the Wiki pane of the **Sharing Team Knowledge using Azure Project Wikis** project, with the content of the **Project Design** wiki selec
Can you please change "On you lab computer" to "On your lab computer". Was there before but then we get it fixed directly.

2021-01-19 15:34 UTC, mkennten requested changes
@unaihuete93 Looks good so far, just some minor changes need to be done. Thank you!

2021-01-20 10:04 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
> +1.  On you lab computer, in the Azure DevOps portal displaying the Wiki pane of the **Sharing Team Knowledge using Azure Project Wikis** project, with the content of the **Project Design** wiki selec
fixed :)

2021-01-20 10:04 UTC, unaihuete93 commented on Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
> +1.  In the vertical menu on the left side, click **Repos**, in the upper section of the **Files** pane, make sure you have  the **TailwindTraders-Website** repo selected (choose it from the dropdown
fixed! :)

2021-01-25 13:21 UTC, unaihuete93 commented
typos fixed :)

2021-02-08 15:05 UTC, mkennten approved these changes

2021-02-08 15:05 UTC, merged