Lab24: renewed for UI updates
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #249
Opened 2022-04-28 16:52 UTC by unaihuete93

**Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes #248  . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [x] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [x] Tested it
- [x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

-
-
-

2022-04-28 20:02 UTC, LuizMacedo commented
Great PR! Thanks, @unaihuete93! If you have time to check, feel free and let us know what you think @mkennten. I'll merge tomorrow.

2022-05-02 09:26 UTC, mkennten requested changes
Look good to me, needs just some minor corrections. Thanks for updating this!

2022-05-02 09:26 UTC, mkennten commented on Instructions/Labs/AZ400_M10_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
> +1.  On the **Add a new Sonarcloud Service Endpoint**, follow the steps mentioned on your Azure DevOps project, give the name **SonarSC** to the service connection, **check** the box for granting acce
Small typo here - clik instead of click

2022-05-02 09:26 UTC, mkennten commented on Instructions/Labs/AZ400_M10_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
> +1.  On the **Analyze with Azure Pipelines** page, in the **Configure Azure Pipelines** section, click **.NET**. This will display a sequence of steps required to **Prepare Analysis Configuration**, *
You will need **these** instructions...

2022-05-02 09:26 UTC, mkennten commented on Instructions/Labs/AZ400_M10_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
> +    > **Note**: We need to change because we have pipelines enabled only for private projects.
This need to be done if you followed the steps in Mod 00 to setup a parallel job for private projects only and your organization currently has no jobs available for public project.

2022-05-03 09:20 UTC, unaihuete93 commented
great comments @mkennten updated it accordingly ;)

2022-05-03 15:07 UTC, merged