Update AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azu…
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #338
Opened 2022-12-10 13:21 UTC by sayedimac

…re_Boards.md

In the previous line, we tell the learners to assign it to themselves - not sure why this is in there twice. If there is a reason it is in there twice, we need to change it to say: "Add page for most recent tutorials" and not "Add page for most recent tutorial"

**Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes # . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [ ] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [ ] Tested it
- [ ] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

-
-
-

2022-12-12 20:31 UTC, LuizMacedo commented
Hi @sayedimac, we can remove Step 4 at Task 3. Just make sure you fix the numbering issue in your change:
![Numbering Issue](https://user-images.githubusercontent.com/45747223/207146345-3641c5ea-230a-4050-8358-e74f885e3884.jpg)

Please, make sure you follow the [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) for the issue creation and test.

Thanks!

2023-01-24 15:44 UTC, unaihuete93 requested changes

2023-01-24 15:45 UTC, unaihuete93 approved these changes

2023-01-24 15:46 UTC, unaihuete93 commented
@LuizMacedo PR should be approved

2023-01-24 21:43 UTC, LuizMacedo approved these changes

2023-01-24 21:43 UTC, merged

2023-01-24 21:43 UTC, LuizMacedo commented
Thanks @sayedimac @unaihuete93!