Update AZ400_M00 and AZ400_M01_L01
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #574
Opened 2024-05-07 20:34 UTC by WigF1

**Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes # . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [x] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [x] Tested it
- [x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

See #573 for the issue.

2024-05-07 21:52 UTC, rob-foulkrod commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +## Estimated timing: 90 minutes
Lab timings are a separate conversation. Please revert.

2024-05-07 21:53 UTC, rob-foulkrod commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Settings** panel, click **Save amd close**.
Correct Spelling

2024-05-07 21:57 UTC, rob-foulkrod commented
Thanks for the contribution. Please be patient while we find time to review.

2024-05-07 22:24 UTC, yashints requested changes
Thanks for your time and contribution

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Backlog** tab of the **EShop-WEB** pane, in the upper left corner of the pane, click the plus sign next to the first work item. This will display the **NEW TASK** panel.
why is the second plus sign removed here?

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. Within the **ToDo** Column, notice the Task Item **Add page for most recent tutorials**, replace the **Unassigned** entry with your user account, then select your account to assign the task to you
revert back please, this version is confusing

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Settings** panel, click **Save amd close**.
typo

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Boards portal**, the **QA Approved** column is now visible in the Kanban board view.
revert back please, notes are rarely read by learners

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: The **QA Approved** stage now has **Doing** and **Done** columns. You can also click the informational symbol (with letter **i** in a circle) next to the column header to read the **D
see above

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: You may need to refresh the browser to make the swimlane visible.
revert back please, they appear immediately

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Dashboards** pane, in the upper-right corner, select **+ New dashboard**.
The new layout is slightly different, if you have time update the instructions and the image (now it's a drop down in the left side)

2024-05-07 22:24 UTC, yashints commented on Instructions/Labs/images/m1/EShop-WEB-pbi_field_layout_v1.png
Is this intentional? I think you saved the image with the wrong name?

2024-05-08 04:02 UTC, WigF1 commented on Instructions/Labs/AZ400_M00_Validate_lab_environment.md
> +
Without the extra line in there, the note is not displayed correctly:

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/17561f7c-4262-46e6-b803-cdf04a41d046)

2024-05-08 04:02 UTC, WigF1 commented on Instructions/Labs/AZ400_M00_Validate_lab_environment.md
> +
Without the extra line in there, the note is not displayed correctly:

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/17561f7c-4262-46e6-b803-cdf04a41d046)

2024-05-08 04:07 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +## Estimated timing: 90 minutes
OK, I will revert it, however, at no point have I ever encountered a student complete this lab in 60 minutes. You need to engage with your MCTs that deliver this content and ask them directly.

2024-05-08 04:09 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: You may need to refresh the browser to make the swimlane visible.
They do not - I literally did this yesterday as I was making changes. The swimlanes did NOT appear.

2024-05-08 04:10 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Boards portal**, the **QA Approved** column is now visible in the Kanban board view.
So why are they so copious in the labs?

2024-05-08 04:10 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: The **QA Approved** stage now has **Doing** and **Done** columns. You can also click the informational symbol (with letter **i** in a circle) next to the column header to read the **D
See above

2024-05-08 04:11 UTC, WigF1 commented on Instructions/Labs/AZ400_M00_Validate_lab_environment.md
> +
Without the extra line, the note is not rendered correctly. All other notes have this.

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/17561f7c-4262-46e6-b803-cdf04a41d046)

2024-05-08 04:11 UTC, WigF1 commented on Instructions/Labs/AZ400_M00_Validate_lab_environment.md
> +
Without the extra line, the note is not rendered correctly. All other notes have this.

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/17561f7c-4262-46e6-b803-cdf04a41d046)

2024-05-08 04:26 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +## Estimated timing: 90 minutes
Roger

2024-05-08 04:27 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Settings** panel, click **Save amd close**.
Corrected

2024-05-08 04:37 UTC, WigF1 commented on Instructions/Labs/images/m1/EShop-WEB-pbi_field_layout_v1.png
Nope.

When the lab steps are followed as written, that image is exactly what students see. If they were instructed to add a field and click 'Add field' and then click 'New group', they would see the image that was in the instructions. However, that's not what the instructions say. The grouping is defined at the same time as the field.

2024-05-08 04:45 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: You may need to refresh the browser to make the swimlane visible.
I just repeated the steps a few more times. Out of 5 times, the swimlanes appeared automatically only once. Is it not possible to leave the note in there? At least when they don't appear, students will know it's simply a refresh?

Students are instructed to do so for the processes earlier in the lab, how is this different?

2024-05-08 04:55 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Backlog** tab of the **EShop-WEB** pane, in the upper left corner of the pane, click the plus sign next to the first work item. This will display the **NEW TASK** panel.
Because the image is incorrect when the lab steps are followed as written. As is indicated by the screenshots included in the lab steps.

If you look at the original image at images/m1/new_task_v1.png, it does not match the ordering of items from the prior image (eshop-web-view_backlog_v1.png) nor does it match the correct order displayed in EShop-WEB-over_capacity_v1.png.

I assume some form of sort had been placed when screenshots were taken. 

In order to achieve the desired result, the task needs adding to the first pbi, not the second.

2024-05-08 04:56 UTC, WigF1 commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. Within the **ToDo** Column, notice the Task Item **Add page for most recent tutorials**, replace the **Unassigned** entry with your user account, then select your account to assign the task to you
There is no list of user accounts displayed when clicking 'Unassigned'. As written, the lab steps do not work.

2024-05-08 08:25 UTC, yashints commented on Instructions/Labs/AZ400_M00_Validate_lab_environment.md
> +
Where are you seeing this? is that in the lab environment or a markdown editor like VS Code?

2024-05-08 08:28 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. On the **Boards portal**, the **QA Approved** column is now visible in the Kanban board view.
I don't get your point, having the refresh in instructions is better than notes no?

2024-05-08 08:31 UTC, yashints commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +1. Within the **ToDo** Column, notice the Task Item **Add page for most recent tutorials**, replace the **Unassigned** entry with your user account, then select your account to assign the task to you
As you correctly mentioned there won't be a user account to select, so the user has to type their name and press enter to see the account. Maybe reword to this instead

2024-05-08 11:52 UTC, rob-foulkrod commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +## Estimated timing: 90 minutes
So you know who you are working with, both Yas and I are MCTs who deliver this course on the regular. We are helping out the content creators in our extra time.

2024-05-08 11:57 UTC, rob-foulkrod commented on Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
> +    > **Note**: The **QA Approved** stage now has **Doing** and **Done** columns. You can also click the informational symbol (with letter **i** in a circle) next to the column header to read the **D
Currently, contributions that correct errors are the most helpful. Edits to style are more arbitrary and debatable and result in unnecessary churn. Keeping the PR smaller and more focused will help us merge it more quickly.

2024-06-13 21:02 UTC, LuizMacedo approved these changes

2024-06-13 21:03 UTC, merged