Lab 19, added changes to Instructions in Exercise 1 Task 2, fix for M…
MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions pull request #84
Opened 2021-06-01 14:59 UTC by preethidoss1221

…aven build.

# Module: 19
## Lab:19 

# Lab 19, added changes to Instructions in Exercise 1 Task 2, Added instructions to fix Maven build by modifying pom.xml. The latest Maven release of 3.8.1 blocks HTTP artifactories, Students will have to use HTTPS instead of HTTP under PluginRepositories section of the pom.xml file.

2021-06-01 14:59 UTC, preethidoss1221 commented
Lab 19, added changes to Instructions in Exercise 1 Task 2, Added instructions to fix Maven build by modifying pom.xml. The latest Maven release of 3.8.1 blocks HTTP artifactories, Students will have to use HTTPS instead of HTTP under PluginRepositories section of the pom.xml file.

2021-06-01 16:00 UTC, FireyJoe commented
I ran this lab and can confirm the problem with HTTP repositories and that the given solution works. Maven 3.8.1 release notes specify the change to disallow unsecure repositories: https://maven.apache.org/docs/3.8.1/release-notes.html. 
![AZ-400 pull 84 comment 1](https://user-images.githubusercontent.com/47234227/120355036-f7203000-c2d0-11eb-9d5a-5b252b3f2c96.JPG)

2021-06-10 19:08 UTC, mkennten requested changes
@preethidoss1221 Can you please run a quick spell/grammar check on our changes. Some examples: Identify (small i), url (all capitals), "Once the **Commit** button is enabled...", Vertical (small v), (please use the previous wording), "the" pom.xml file...

2021-06-15 10:00 UTC, preethidoss1221 commented
@mkennten  - Requesting for a review on commit id: c955de8 ,I have incorporated sentence correction. Thank you for your review.

2021-06-22 16:23 UTC, mkennten requested changes
Hi, please correct the issues I commented on

2021-06-22 16:23 UTC, mkennten commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +    > **Note**: As the project uses Maven to compile the project files, latest Maven release of 3.8.1 blocks HTTP artifactories. To successfully build the project, you will have to change the pom.xml
"the" latest Maven release

2021-06-22 16:23 UTC, mkennten commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +    > **Note**: As the project uses Maven to compile the project files, latest Maven release of 3.8.1 blocks HTTP artifactories. To successfully build the project, you will have to change the pom.xml
file of the Project ==> file of the project

2021-06-22 16:23 UTC, mkennten commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +    > **Note**: As the project uses Maven to compile the project files, latest Maven release of 3.8.1 blocks HTTP artifactories. To successfully build the project, you will have to change the pom.xml
"Perform below steps" (plural)

2021-06-22 16:23 UTC, mkennten commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +1. Inside **webgoat-container** project file, identify the pom.xml file and click on **Edit** on the top right corner. Search for the section **pluginRepositories** inside the pom.xml file. Change th
"Inside the **webgoat-container** project file"

2021-06-22 16:23 UTC, mkennten commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +1. In the vertical menu bar on the left side, navigate to **Pipelines** section and click **Pipelines**. Observe the build, while it has automatically triggered due to the commit action performed in
"navigate to the **Pipelines** section"
"while it has  been automatically triggered by the commit performed in the previous step."

2021-06-24 15:43 UTC, preethidoss1221 commented on Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
> +1. In the vertical menu bar on the left side, navigate to **Pipelines** section and click **Pipelines**. Observe the build, while it has automatically triggered due to the commit action performed in
Fixed additional sentence corrections at commit id: a541e0f . Thank you @mkennten for the review and guidance.

2021-06-29 09:21 UTC, mkennten approved these changes

2021-06-29 09:21 UTC, merged